### ISSUE TITLE
Ledger: Avoid confirming wallet address at each operation

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-react-wallet#127]
Hello,

I've seen that every time we want to create a new transaction through ledger nano s, the wallet requires the address to be verified on ledger end.

This is not needed (for now) as the ledger address that we want to use to sign the tx is also shown on the confirmation steps on the ledger.

**Comment by vekexasia** [comment]
I was referring to 2. Apparently I own a faulty cable and somehow when voting it asked me to confirm my account (& then it started the voting flow.)

**Comment by roosmaa** [comment]
Ok, able to reproduce as well, but it isn't the voting that's causing it. It's the settings screen - whenever you enter it, it triggers the address verification. It would seem that #115 implementation is buggy.

**Comment by TobiaszCudnik** [comment]
Related to rendering dialogs before they are open, like #94 
- introduced dialog open/close handlers with 4974b409721f4bcb00fa82a216859ac45f6f849a
- disabled ledger communication error handler for now (causes flooding)

Created  #137 to address problematic bits related to the ledger integration.
