### ISSUE TITLE
Cant set a second passphrase when no public key

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#128]
Cant set a second passphrase if the account doesnt have a public key (fresh account with some funds transferred in):
```
Unhandled Rejection (TypeError): First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```

**Comment by TobiaszCudnik** [comment]
Solution is to store a derived publicKey after the user inputs the mnemonic when confirming a transaction.

**Comment by roosmaa** [comment]
A beta tester is hitting this bug - unable to send funds from their accounts. The send dialog gets stuck in broadcasting state.

```
index.js:311 Uncaught (in promise) TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
   at index.js:311
   at l (index.js:137)
   at Function.u.from (index.js:149)
   at t.toSenderObject (account.ts:96)
   at t.<anonymous> (wallet.ts:186)
   at onboarding.ts:3
   at Object.next (onboarding.ts:3)
   at onboarding.ts:3
   at new Promise (<anonymous>)
   at y (onboarding.ts:3)
```

The content of local storage is: 

```
[{"id":"13274079971249639453R","publicKey":null,"type":1,"hwId":null,"hwSlot":null,"fiatCurrency":"USD","name":"Ipsumxtestnet","pinned":false}]
```

I was able to reproduce by:
- Creating a new account
- Signing out
- Adding existing account

But tester hit this with both not signing out and with signing out. Anyway, we know how to fix this just wanted to mirror here all the information gathered via Slack :)
