### ISSUE TITLE
Notification the user when the service worker has finished downloading a new version

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#132]
It would be good to have a notification show up and inform the user that a new version of the web app is available and that they need to refresh to switch to it. Like the Facebook Messenger does it. Without notification the users (especially testers) would not be sure if they're using the latest version or not.

It would have to hook into the (create-react-app generated) service worker to listen to events when the download of the new version is complete. Visually the notification could mimic the new release notification on [material-ui.com](https://material-ui.com/):

![Screenshot of a notification on Material UI website](https://user-images.githubusercontent.com/65596/48195398-d75e4080-e34f-11e8-9fc5-12b154db66d5.png)

**Comment by TobiaszCudnik** [comment]
@roosmaa I've implemented a notification based on `console.log('New content is available; please refresh.')`, but couldn't validate that it's actually working. Am I missing something?

**Comment by roosmaa** [comment]
Tbh, I don't have a clear idea about that either.

You probably know this already, but... what you do need to watch out is that this cannot really be tested on development server - create react app doesn't include the proper service worker for non-production environments.

**Comment by TobiaszCudnik** [comment]
Checked using
- `yarn build`
- `yarn run serve`
- visit
- code change
- `yarn build`
- `yarn run serve`
- visit

Nothing, `onupdatefound` not fired.
