### ISSUE TITLE
After setting up 2nd passphrase, the wallet doesn't prompt for it right after

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#134]
A beta tester reported this bug.

> When casing a vote for a delegate for the first time, the Confirmation transaction screen only allows for the Account mnemonic secret and not the 2nd passphrase. Thus the transaction Fails. Going back into "Voted delegate" the Second passphrase displays and allows for the entry. I tested this across 2 new accounts and had the same issue with each of them.

The with which I can reproduce:

1) Create new account
2) Use faucet to get RISE to the account
3) Refresh page to see that the RISE has arrived
4) Setup 2nd passphrase
5) Wait a bit, but do NOT refreshing the page
6) Attempting to vote
7) Vote process only asks for the mnemonic
8) Submitting the transaction fails

If in step 5 you wait too little, then the tx doesn't error out, the node accepts it and can potentially apply it, but most likely it'll get dropped silently.

The source of the issue is that we don't really update the local state of the account. So when the user sends off transactions we don't know that the account has a public key associated with it until they refresh the page / reload the account data.

**Comment by TobiaszCudnik** [comment]
Fixed with 1d5b87864b61de635a9065edc03a2ce6b824bc2d.
