### ISSUE TITLE
Clarify what the pinned account setting does

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#136]
Currently it's not completely clear what the pinned account setting does. The fact that the accounts list UI isn't implemented yet, doesn't help either. But we should find a way to communicate to the users what it does. Either by introducing an icon to the pinned accounts in the drawer and/or adding some explanatory text to the setting. Maybe even just show the setting after the user has added more than N accounts. (where N is the amount after which we start truncating the accounts in the sidebar)

**Comment by TobiaszCudnik** [comment]
"Pin account" setting shows up now once the amount of added accounts is bigger or equal to `config.max_drawer_accounts` - 087c68a7fad78e5d3e473a9aee6886d8cd9e2e4e.

**Comment by roosmaa** [comment]
I tried to add an indicator into the drawer, but it didn't look nice. So I guess for the time being let's just leave it at hiding the setting for low account wallets.
