### ISSUE TITLE
Auto-select the close button on last step of transaction confirmation flow

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#140]
From a tester:

> When processing a transaction, pressing [enter] allows you to proceed through each subsequent step, except for the final screen when you need to click "close".  It would be nice to just hit enter on the final screen to close the "Confirm transaction" window.

**Comment by TobiaszCudnik** [comment]
Fixed with 7a16f0317d216126454b1788281e5cb53de1f54a.
