### ISSUE TITLE
Make the release bundle independent from the config

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#145]
Currently when making a release the config gets bundled with the whole release, thus we need to make 2 separate ones (with the same code) for the testnet and mainnet.

Having the config loaded separately would make this process simpler.

Low priority.

**Comment by roosmaa** [comment]
Possibly even inject the config from the `index.html`? That way the deploy script can easily just substitute the values in index.html and there's no extra request to load the config.

**Comment by TobiaszCudnik** [comment]
Bunding the config with `index.html` wont solve having 2 separate releases.

I think a network switcher with some domain autodetection would solve both:
- one release
- no network request

By autodetection I mean:
- in case of `twallet` in the url, `api_url` gets set to `https://twallet.rise.vision`
- everything else goes to `https://wallet.rise.vision`
- UI switcher is optional, but nice to have

**Comment by TobiaszCudnik** [comment]
`mainnet` auto-detection rules:
- if on the deployment domain (config), and `wallet` sub-domain == `mainnet`
- anything else == `testnet`

**Comment by vekexasia** [comment]
Is there a way for anyone else to specify their own backend?

**Comment by TobiaszCudnik** [comment]
Yes, according to a couple of [config values](https://github.com/RiseVision/rise-react-wallet/blob/master/src/stores/index.ts#L10).

**Comment by vekexasia** [comment]
@TobiaszCudnik can we make that clear in readme as well?

**Comment by TobiaszCudnik** [comment]
@vekexasia Fixed with https://github.com/RiseVision/rise-react-wallet/commit/322813efb726f86e28ebff661778ce8520f9deb2.

**Comment by roosmaa** [comment]
@TobiaszCudnik why did we go with the magic auto-detect method, instead of providing the configuration via a global settings object defined in index.html (which would be easy to override for everyone downloading the release package)?

(this change semi-broke unconfirmed transaction loading, on my dev-server all data is loaded from testnet node, but the unconfirmed is loaded from mainnet)

**Comment by TobiaszCudnik** [comment]
> why did we go with the magic auto-detect method, instead of providing the configuration via a global settings object defined in index.html

It was the easiest way which involved zero editing, thus making "the release bundle independed from the config" (like the title of this ticket).

Next step will be providing a node switcher #151.

Editing `index.html` isn't an elegant solution. 

> this change semi-broke unconfirmed transaction loading; on my dev-server all data is loaded from testnet node, with the exception of unconfirmed transactions - that is loaded from mainnet. Meaning the autodetection is failing

True, unconfirmed transactions are done by a direct request (instead of `dpos-offline`). Fixed with 1a3e0233708984b009bc724852fa9efd9ecb19b3.

**Comment by roosmaa** [comment]
The current approach only makes it "independent from config" for 2 of our public domains. If someone other than us was to take the release from Github, it would basically be impossible for them to actually deploy the bundles. Having someone take the bundles and deploy with ease seems to be the core motivation for this change, but the current auto-detection approach doesn't really provide a solution for this.

**Comment by TobiaszCudnik** [comment]
There's 3 use cases:

1. Our own deployments (handled by the domain auto detection)
2. External deployments (for this overriding the config in `index.html` will be useful)
3. End user changing the network (UI switcher #151)

I agree with the 2nd, but not by making the editing mandatory for our own deployments.
