### ISSUE TITLE
Storing encrypted secrets locally to improve UX on mobile

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#147]
One of our beta testers pointed out that on mobile it's very annoying to enter the mnemonic for every transaction. They suggested storing the encrypted mnemonic locally with PIN access. A PIN would be significantly better UX, but also easier to brute force. (Of course some of it could be mitigated by selecting a high enough iterations count in the key derivation algorithm). A better option would be to utilise the secure enclave of the devices somehow (with fingerprint authentication), but that would require native applications and not work with a PWA.

If we were to implement the PIN option, we would probably want to mark the account as somewhat less secure. Ideally that marking shouldn't be local, rather have some API on our servers which keeps track of those accounts. And then we will display warnings to the user when they are using the account. One permanent place that doesn't jump out, but also display a big visible warning if the account balance goes over a threshold.

**Comment by TobiaszCudnik** [comment]
On iOS, the password manager works in the browser and authenticates using the fingerprint. Not sure about android, but should be similar.

That said, things should be just working at the moment, although I'm not sure about the support for a double password field...

**Comment by TobiaszCudnik** [comment]
Implemented with a single password field at a time. One iOS its required to add a name to the saved password.

Tested on iOS, Android should work better. Video below:
[![Watch the video](https://i9.ytimg.com/vi/pYP8_pcs418/mq3.jpg?sqp=CLjx2t8F&rs=AOn4CLAGC4Q01yn4u4B7LIweqi95EvlWng)](https://youtu.be/pYP8_pcs418)
