### ISSUE TITLE
Branding for the fiat conversion provider

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#148]
#33 implements fiat conversions coming from http://coingecko.com/api, which suggest a backlink and provides some [branding guidelines](https://www.coingecko.com/en/branding).

**Comment by roosmaa** [comment]
For now, we could just use the `<Tooltip />` component for the displayed FIAT amount, which displays "Powered by CoinGecko" (as suggested by the guidelines).
