### ISSUE TITLE
No length limit for account names

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#158]
No length limit for account names.

![przechwytywanie](https://user-images.githubusercontent.com/93027/50145398-c6d7a900-02b1-11e9-94f1-c8371009b76c.PNG)

**Comment by roosmaa** [comment]
If the user want's to break their own interface, I say let them go for it.

**Comment by roosmaa** [comment]
Closing this as wont fix, as it only impacts users who do this to themselves.
