### ISSUE TITLE
Service-worker in Carlo?

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-react-wallet#164]
I saw in one of the issues an error about service worker registration. But in Carlo context, the service worker doesn't make much sense to me. It can potentially only introduce bugs (eg. the user updates the desktop binary and has to restart it because service worker still had the old assets cached [hypothetical, haven't tested]). So maybe we should not register the service worker when running in Carlo context?

// @TobiaszCudnik

**Comment by TobiaszCudnik** [comment]
Yes, ideally we would backport [this PR](https://github.com/facebook/create-react-app/pull/3817) with `typeof carlo` detection.
