### ISSUE TITLE
Autonaming accounts

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-react-wallet#166]
Can we polish the account naming procedure a little bit? 

Here 2 proposals:

1) Auto assign a name with a counter like: 
  - Account 1
  - Account 2 ....

2) Ask user to name account just right after he adds it via a dialog (With some default - See proposal above?)

I don't like 2 much but people having several accounts and working with different machines would love this.

**Comment by roosmaa** [comment]
The auto naming doesn't really help the use-case you pointed out. For it to "work", they would have to add the accounts on the 2nd computer in the same order for the labels to match. Account image is more helpful in that case.

We could potentially a button into the account overview header that would allow people to quickly rename accounts (without going to the settings).

**Comment by vekexasia** [comment]
My usecase is ledger accounts. Usually one would re-add them in the same sequence as they're presented in the UI.

I would still prefer to have account 1,2,... than having N * "Unknown account"s
