### ISSUE TITLE
Visual representation of network 

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-react-wallet#168]
I've just deployed the last 1.0.0 web wallet and it looks like it automatically used testnet even when browsing wallet-beta.rise.vision.

It would be nice to have a visual representation of the current network: (Main, test, custom?)

**Comment by TobiaszCudnik** [comment]
Ive fixed mainnet autodetection and reverted aa235d69490675ca96ea4d159f09dc69de4ed6eb which hid the node switcher on the (official) web.
