### ISSUE TITLE
when second passphrase is choosen, none is automatically proposed

### ISSUE THREAD

**Issue by corsaro1** [RiseVision/rise-react-wallet#181]
if you try to set on an existing address a second passphrase, none is proposed

**Comment by TobiaszCudnik** [comment]
I'm afraid I don't understand this report.

Are you referring to:
1. Setting a new passphrase?
2. Password manager proposing a remembered passphrase when signing a transaction?

Please clarify so we can help. Steps to reproduce your problem is the best way to describe it.
