### ISSUE TITLE
Vote transactions with empty `votes` break the wallet

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#189]
Vote transactions with empty `votes` break the wallet.

Reported on slack by Vergill:
```
TypeError: Cannot read property 'filter' of undefined
   at t.getSummary (TxDetailsExpansionPanel.tsx:703)
```

**Comment by vekexasia** [comment]
I'm pretty sure you can close this. Last week i was working on wallet.rise.vision and `/api/transactions/` was not returning any Asset.
