### ISSUE TITLE
Avoid rounding send amounts

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-react-wallet#199]
Tried to initialize wallet with account 0R which received only one tx of 1 sat.

On desktop version i get `Send amount: 0 RISE`.

Tx is : https://explorer.rise.vision/tx/8329226211113767041

**Comment by TobiaszCudnik** [comment]
Not sure about the explorer, but from the API point these are the numbers:
- `100000000` amount (1 RISE)
- `10000000` fee (0.1 RISE)

Which means the number handling is correct. Is there a missing `unit` field for the amount?

**Comment by vekexasia** [comment]
![image](https://user-images.githubusercontent.com/200523/52057527-85e7db00-2565-11e9-99b3-94735f99b7b7.png)

**Comment by TobiaszCudnik** [comment]
Reproduced on the `mainnet`.
