### ISSUE TITLE
Suggest mobile users to install the app to home screen

### ISSUE THREAD

**Issue by TobiaszCudnik** [RiseVision/rise-react-wallet#215]
Currently many users don't realize they can install the PWA as any other app on both Android and iOS. This is even more true with offline support coming in `1.1`. We should promote this and guide mobile users:
- [x] detect mobile users
- [x] detect home screen users
- [x] button in on-boarding
- [x] button in the left menu
- [x] landing page
- [x] support for `beforeinstallprompt`

Somehow related to #177, as the home screen app doesn't retain the previous data.

Related [pull request](https://github.com/RiseVision/rise-react-wallet/pull/218).

**Comment by roosmaa** [comment]
On Android Chrome actually shows the "Add to desktop" banner automatically already.

**Comment by TobiaszCudnik** [comment]
That's true, support for PWAs is still inconsistent. The other problem is lack of user awareness resulting in complains "you don't have a native/mobile app". My point is, the banner itself isn't enough.

Also related to #186.
